### ISSUE TITLE
__init__() got an unexpected keyword argument 'capabilities'

### ISSUE THREAD

**Issue by b0fhb0fh** [RedSiege/EyeWitness#615]
## OS Used - ALL Information (architecture, linux flavor, etc.)
kali , debian
Linux kali 6.1.0-kali9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux
Linux scan01 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

I tried apt install, git clone / setup.sh , docker 29.06.2023
and I've got the same error

## Pastebin link to error you are encountering
__init__() got an unexpected keyword argument 'capabilities'
[*] No report files found to open, perhaps no hosts were successful

**Comment by b0fhb0fh** [comment]
ooops, looks like previous issue #614

**Comment by paulmartinmt** [comment]
The issue looks to be with the recent Selenium python package 4.10.0. Downgrading that to 4.9.0 resolved the issue for me on Ubuntu 20.04 

#show python packages 
pip list

#uninstall selenium if it is version 4.10.0
pip uninstall selenium

#install 4.9.0 as that version works with eyewitness 
pip install selenium==4.9.0

**Comment by Bitrotator** [comment]
Hi,
my temporary solution to avoid that error is:
In file: EyeWitness/Python/modules/selenium_module.py change
line 79 as noted:

#driver = webdriver.Firefox(profile, capabilities=capabilities, options=options, service_log_path=cli_parsed.selenium_log_path)
driver = webdriver.Firefox()

**Comment by digininja** [comment]
Did you try to work out which of those parameters was causing the problem?

**Comment by Bitrotator** [comment]
Hi,
not now, i needed a fast fix :) ... i can take a look at it if you
need that information ... maybe today at night... dunno exactly....



Am Fr., 30. Juni 2023 um 10:16 Uhr schrieb Robin Wood <
***@***.***>:

> Did you try to work out which of those parameters was causing the problem?
>

**Comment by Bitrotator** [comment]
Hi,
fast check on API Interface within ipython3 (python3.8)

webdriver.Firefox(
    options: selenium.webdriver.firefox.options.Options = None,
    service: selenium.webdriver.firefox.service.Service = None,
    keep_alive=True,
) -> None

ipython3.8

In [1]: from selenium import webdriver


In [2]: ?webdriver.Firefox

Init signature:
webdriver.Firefox(
    options: selenium.webdriver.firefox.options.Options = None,
    service: selenium.webdriver.firefox.service.Service = None,
    keep_alive=True,
) -> None
Docstring:      Controls the GeckoDriver and allows you to drive the
browser.
Init docstring:
Creates a new instance of the Firefox driver. Starts the service and
then creates new instance of Firefox driver.

:Args:
 - options - Instance of ``options.Options``.
 - service - (Optional) service instance for managing the starting and
stopping of the driver.
 - keep_alive - Whether to configure remote_connection.RemoteConnection to
use HTTP keep-alive.
File:
/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py
Type:           ABCMeta
Subclasses:

Am Fr., 30. Juni 2023 um 14:45 Uhr schrieb Oliver Hable ***@***.***
>:

> Hi,
> not now, i needed a fast fix :) ... i can take a look at it if you
> need that information ... maybe today at night... dunno exactly....
>
>
>
> Am Fr., 30. Juni 2023 um 10:16 Uhr schrieb Robin Wood <
> ***@***.***>:
>
>> Did you try to work out which of those parameters was causing the
>> problem?
>>

**Comment by digininja** [comment]
I was just thinking about taking one option out at a time to test it.

I'm away from a PC for the weekend so can't test anything.

**Comment by fabifighter007** [comment]
Getting the same errors. Were you able to find a fix?

**Comment by ChrisTruncer** [comment]
This should now be fixed in the setup script, right now it's hard coding the version of selenium to use

**Comment by digininja** [comment]
This isn't fixed on Kali as it uses the apt version of the selenium library which is the broken version. I just got my Kali box working by:

```
apt remove python3-selenium
pip3 install selenium==4.9.0
```

Mixing pip3 and apt is probably not a good idea, but it is working for now.

**Comment by ChrisTruncer** [comment]
just switched this around, using 4.9.1, but SHOULD be good on Kali now too.
